// src/components/Category/Form.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import axios from '@/module/Axios'
	import Toaster from '@/components/Toast';
	import type { AxiosResponse } from 'axios';
	import type { ICategory, IForm } from './interface';
  const dispatch = createEventDispatcher()

  
  export let category: ICategory|undefined = undefined
  let busy: boolean = false
  let form: IForm = {
    title: '',
    slug: ''
  }

  onMount(() => {
    if (category) {
      form = {
        title: category.title,
        slug: category.slug
      }
    }
  })

  const submitForm = async () => {
    busy = true

    try {
      const response = await (category !== undefined ? update() : create())
      Toaster.success('categories created')

      dispatch('submit', response.data)
    } catch (e) {
      Toaster.danger('failed creating store')
    }

    busy = false
  }

  const create = () :Promise<AxiosResponse> => {
    return axios.post('/categories', form)
  }

  const update = () :Promise<AxiosResponse> => {
    if (category === undefined)
      throw Error()

    return axios.put(`/categories/${category.id}`, form)
    
  }
</script>

<form method="post" on:submit|preventDefault={submitForm}>
  <div class="form-group">
    <label for="">title</label>
    <input type="text" class="form-control" bind:value={form.title} />
  </div>

  <div class="form-group">
    <label for="">Slug</label>
    <input type="text" class="form-control" bind:value={form.slug} />
  </div>

  <button type="submit">{ busy ? 'Wating...' : 'Submit' }</button>
</form>

// src/components/Category/Form.vue
<script lang="ts">
interface State {
  title: string,
  slug: string
}
</script>

<script lang="ts" setup>
import type { Category, Form } from '@/interface';
import type { IToaster } from '@/plugins/toast';
import type { AxiosInstance, AxiosResponse } from 'axios';
import { reactive, inject, type PropType, onMounted } from 'vue';
const emit = defineEmits<{
  (e: 'onSubmit', category: Category): void
}>()
const axios = inject('axios') as AxiosInstance
const toaster = inject('toaster') as IToaster
const { category } = defineProps({ category: { type: Object as PropType<Category>, required: false } })

const state = reactive<State & Form>({ title: '', slug: '', busy: false })

const store = async () :Promise<AxiosResponse> => {
  return await axios.post('/categories', { title: state.title, slug: state.slug })
}

const update = async () :Promise<AxiosResponse> => {
  return await axios.put(`/categories/${category?.id}`)
}

onMounted(() => {
  if (category) {
    state.title = category.title
    state.slug = category.slug
  }
})

const onSubmit = async () => {
  state.busy = true

  try {
    let response: AxiosResponse
    if (category?.id)
      response = await update()
    else
      response = await store()

    toaster.success('Category Store Successfully')
    state.title = ''
    state.slug = ''

    emit('onSubmit', response.data)
  } catch (e: any) {
    if (e.response)
      toaster.danger(e.response.data.message)
    else
      toaster.danger('Error on server connection')
  }

  state.busy = false
}
</script>

<template>
<form class="my-7" @submit.prevent="onSubmit">
  <div class="flex flex-col mb-4">
    <label for="categories-title" class="mb-3">Title</label>
    <input id="categories-title" v-model="state.title" type="text" class="input" />
  </div>

  <div class="flex flex-col">
    <label for="categories-slug" class="mb-3">Slug</label>
    <input id="categories-slug" v-model="state.slug" type="text" class="input" />
  </div>

  <button type="submit" class="mt-4 btn-submit">
    Submit
  </button>
</form>
</template>
