// src/components/Category/Form.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import { create, update, type ICategory } from '@/api/categories'
	import Toaster from '@/components/Toast';
	import type { IForm } from './interface';
  const dispatch = createEventDispatcher()

  
  export let category: ICategory|undefined = undefined
  let busy: boolean = false
  let form: IForm = {
    title: '',
    slug: ''
  }

  onMount(() => {
    if (category) {
      form = {
        title: category.title,
        slug: category.slug
      }
    }
  })

  const submitForm = async () => {
    busy = true

    try {
      const response = await (category !== undefined ? update(category.id, form) : create(form))
      Toaster.success('categories created')

      dispatch('submit', response.data)
    } catch (e) {
      Toaster.danger('failed creating store')
    }

    busy = false
  }
</script>

<form method="post" on:submit|preventDefault={submitForm}>
  <div class="form-group">
    <label for="">title</label>
    <input type="text" class="form-control" bind:value={form.title} />
  </div>

  <div class="form-group">
    <label for="">Slug</label>
    <input type="text" class="form-control" bind:value={form.slug} />
  </div>

  <button type="submit">{ busy ? 'Wating...' : 'Submit' }</button>
</form>

// src/components/Category/Form.tsx
import { useState } from 'react'
import { Form } from 'react-router-dom'
import Axios from '../../plugins/axios'

interface IState {
  title: string
  slug: string
  description: string
}

export default () => {
  const [form, setForm] = useState<IState>({ title: '', slug: '', description: '' })

  const submitForm = async (e: any) => {
    e.preventDefault()

    const response = await Axios.post('/categories', { ...form })

    console.log(response)
  }

  return (
    <Form method='post' onSubmit={ submitForm }>
      <div className='form-group'>
        <label htmlFor="title">Title</label>
        <input type="text" id='title' className='input-control' defaultValue={ form.title } onChange={ e => setForm({ ...form, title: e.currentTarget.value }) } />
      </div>

      <div className='form-group'>
        <label htmlFor="slug">Slug</label>
        <input type="text" id='slug' className='input-control' defaultValue={ form.slug } onChange={ e => setForm({ ...form, slug: e.currentTarget.value }) } />
      </div>

      <div className='form-group'>
        <label htmlFor="description">Description</label>
        <textarea className='input-control' defaultValue={ form.description } onChange={ e => setForm({ ...form, description: e.currentTarget.value }) }></textarea>
      </div>

      <button type='submit' className='py-3 px-7 bg-green-600 text-white rounded hover:bg-green-800 transition'>Submit</button>
    </Form>
  )
}
