// src/components/Post/Form.tsx
import Axios from '@/plugins/axios'
import { useState } from "react"

export interface IPostForm {
  id?: string
  title: string,
  body: string
}

export interface IFormProps {
  post: IPostForm
}

export default (props: IPostForm | null) => {
  const [ form, setForm ] = useState<IPostForm>({ title: '', body: ''})

  const update = async () :Promise<void> => {
    return await Axios.post(`/posts/${form.id}`, form)
  }

  const create = async () :Promise<void> => {
    return await Axios.post('/posts', form)
  }

  const onSubmit = async (e: any) => {
    e.preventDefault()

    if (props) {
      await update()
    } else
      await create()
  }


  return (
    <form onSubmit={ onSubmit }>
      <div className="flex flex-col mb-4">
        <label htmlFor="posttitle" className="mb-2">Post title: </label>
        <input id="posttitle" type="text" className="input" onChange={ e => setForm({ ...form, title: e.currentTarget.value}) } />
      </div>

      <div className="flex flex-col mb-4">
        <label htmlFor="postBody" className="mb-2">Content: </label>
        <textarea id="postBody" rows={10} className="py-2 px-3 border rounded" onChange={ e => setForm({ ...form, body: e.currentTarget.value })}></textarea>
      </div>

      <button type="submit" className="py-3 px-6 bg-green-500 rounded text-white">Submit</button>
    </form>
  )
}

// src/components/Post/Form.vue
<script lang="ts">
interface Post {
  id?: string
  title: string,
  body: string
}
</script>

<script lang="ts" setup>
import type { IToaster } from '@/plugins/toast';
import type { AxiosInstance, AxiosResponse } from 'axios';
import { inject, reactive, type PropType } from 'vue';
const axios = inject('axios') as AxiosInstance
const toaster = inject('toaster') as IToaster

const emit = defineEmits<{
  (e: 'onStore', post: any): void
}>()

const props = defineProps({ post: { type: Object as PropType<Post>, required: false, default: null } })

const form = reactive<Post>({
  title: props.post?.title,
  body: props.post?.body
})

const store = async (): Promise<AxiosResponse> => {
  return await axios.post('/posts', form)
}

const update = async (): Promise<AxiosResponse> => {
  return await axios.put(`/posts/${props.post.id}`, form)
}

const onSubmit = async () => {
  try {
    let response = null
    if (props.post.id)
      response = await update()
    else
      response = await store()

    
    toaster.success('post Store successFully')
    emit('onStore', response.data)
  } catch (e: any) {
    if (e.response) {
      return toaster.danger(e.response.data.message)
    }

    return toaster.danger('uncatched error happend')
  }
}
</script>

<template>
  <form @submit.prevent="onSubmit">
    <div class="flex flex-col mb-4">
      <label for="posttitle" class="mb-2">Post title: </label>
      <input id="posttitle" type="text" v-model="form.title" class="input" />
    </div>

    <div class="flex flex-col mb-4">
      <label for="postBody" class="mb-2">Content: </label>
      <textarea id="postBody" rows="10" v-model="form.body" class="py-2 px-3 border rounded"></textarea>
    </div>

    <button type="submit" class="py-3 px-6 bg-green-500 rounded text-white">Submit</button>
  </form>
</template>
