// src/components/Category/Form.vue
<script lang="ts">
interface State {
  title: string,
  slug: string
}
</script>

<script lang="ts" setup>
import type { Category, Form } from '@/interface';
import type { IToaster } from '@/plugins/toast';
import type { AxiosInstance, AxiosResponse } from 'axios';
import { reactive, inject, type PropType, onMounted } from 'vue';
const emit = defineEmits<{
  (e: 'onSubmit', category: Category): void
}>()
const axios = inject('axios') as AxiosInstance
const toaster = inject('toaster') as IToaster
const { category } = defineProps({ category: { type: Object as PropType<Category>, required: false } })

const state = reactive<State & Form>({ title: '', slug: '', busy: false })

const store = async () :Promise<AxiosResponse> => {
  return await axios.post('/categories', { title: state.title, slug: state.slug })
}

const update = async () :Promise<AxiosResponse> => {
  return await axios.put(`/categories/${category?.id}`)
}

onMounted(() => {
  if (category) {
    state.title = category.title
    state.slug = category.slug
  }
})

const onSubmit = async () => {
  state.busy = true

  try {
    let response: AxiosResponse
    if (category?.id)
      response = await update()
    else
      response = await store()

    toaster.success('Category Store Successfully')
    state.title = ''
    state.slug = ''

    emit('onSubmit', response.data)
  } catch (e: any) {
    if (e.response)
      toaster.danger(e.response.data.message)
    else
      toaster.danger('Error on server connection')
  }

  state.busy = false
}
</script>

<template>
<form class="my-7" @submit.prevent="onSubmit">
  <div class="flex flex-col mb-4">
    <label for="categories-title" class="mb-3">Title</label>
    <input id="categories-title" v-model="state.title" type="text" class="input" />
  </div>

  <div class="flex flex-col">
    <label for="categories-slug" class="mb-3">Slug</label>
    <input id="categories-slug" v-model="state.slug" type="text" class="input" />
  </div>

  <button type="submit" class="mt-4 btn-submit">
    Submit
  </button>
</form>
</template>

// src/components/Post/Form.svelte
<script lang="ts">
  import { createEventDispatcher, onMount } from 'svelte'
  import axios from '@/module/Axios'
	import Toaster from '../Toast';
  import type { IPost } from './interface'

  const dispatch = createEventDispatcher()

  let busy: boolean = false
  export let post: IPost|undefined = undefined
  let form: IPost = {
    title: '',
    slug: '',
    shortDesc: '',
    body: '',
    category: null
  }

  onMount(() => {
    if (post)
      form = {...post}
  })

  const handleSubmit = async () => {
    busy = true

    try {
      const response = await (post ? update() : create())

      Toaster.success('Post Created')
      dispatch('submit', response.data)
    } catch(e) {
      Toaster.danger('Failed On Submit Form')
    }

    busy = false
  }

  const create = () => {
    return axios.post(`/posts`, form)
  }

  const update = () => {
    return axios.put(`/posts/${post?.id}`, form)
  }
</script>

<form method="post" on:submit|preventDefault={handleSubmit}>
  <div>
    <label for="">title</label>
    <input type="text" bind:value={form.title} />
  </div>

  <div>
    <label for="">Slug</label>
    <input type="text" bind:value={form.slug} />
  </div>

  <div>
    <label for="">Short Description</label>
    <input type="text" bind:value={form.shortDesc} />
  </div>

  <div>
    <label for="">Content</label>
    <textarea bind:value={form.body}></textarea>
  </div>

  <button>{ busy ? 'Wating...' : 'Submit' }</button>
</form>
